### ISSUE TITLE
The training data  'audio/park-vienna-105-2983-6-s1.wav' is seemly empty.

### ISSUE THREAD

**Issue by Rockyman-star** [CPJKU/dcase2024_task1_baseline#2]
I tried to train the model with the full setting, but got such en error in the following.
```
Traceback (most recent call last):
  File "/home/zhaoy/dcase2024_task1_baseline/run_training_no_wandb.py", line 507, in <module>
    train(args)
  File "/home/zhaoy/dcase2024_task1_baseline/run_training_no_wandb.py", line 362, in train
    trainer.fit(pl_module, train_dl, test_dl)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1033, in _run_stage
    self.fit_loop.run()
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 212, in advance
    batch, _, __ = next(data_fetcher)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 78, in __next__
    out[i] = next(self.iterators[i])
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 5.
Original Traceback (most recent call last):
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/zhaoy/anaconda3/envs/d24_t1/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 162, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable
```
According the RuntimeError, it seems that some of training data has wrong size so that the dataloader can't work properly when loading batches of audios. After printing the shape of every training data, I figured out that the training data  'audio/park-vienna-105-2983-6-s1.wav'  is empty. The ipython test code is listed as follows!

```
>>> import torchaudio
>>> data = torchaudio.load('audio/park-vienna-105-2983-6-s1.wav')
>>> print(data)
(tensor([], size=(1, 0)), 44100)
```

**Comment by OptimusPrimus** [comment]
Hey, thanks for pointing this out!

We'll try to replace this file. For now, you can probably just train without it.

Best,
Paul

**Comment by fschmid56** [comment]
Hi @Rockyman-star!

We checked the file again today, and it seems okay (judging by listening to it). 

However, we encounter the same error that you describe if we use a conda environment without a proper torchaudio backend installed. By any chance, do you get a warning message similar to the following when importing torchaudio?

`/home/fschmid/miniconda3/envs/dcase24_baseline/lib/python3.8/site-packages/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
`

Can you check if you have a proper torchaudio backend installed?

Best,
Florian

**Comment by fschmid56** [comment]
I'm glad to hear that this resolved the problem!
